name: SonarQube Analysis and Comment

on: [pull_request]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: SonarQube Analysis on Overall Code
        continue-on-error: true
        run: |
          mvn sonar:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.host.url=${{ env.SONAR_HOST_URL }} -Dsonar.login=${{ env.SONAR_TOKEN }} -Dsonar.sources=src -Dsonar.branch.name=${{ github.head_ref }} -Dsonar.qualitygate.wait=true

      - name: Check Quality Gates on overall code
        id: QG_check
        run: |
          status=$(curl -u ${{ env.SONAR_TOKEN }}: '${{ env.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}&branch=${{ github.head_ref }}')
          echo "Quality Gates Status on overall code: $status"

          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Branch Name: ${{ github.head_ref }}"
          sed -i "s|{{SONAR_PREPROD_URL}}|${{ env.SONAR_PREPROD_URL }}|g" ./.github/workflows/overall_code_analysis_decoration.md
          sed -i "s|{{github.head_ref}}|${{ github.head_ref }}|g" ./.github/workflows/overall_code_analysis_decoration.md
          sed -i "s|{{SONAR_PROJECT_KEY}}|${{ env.SONAR_PROJECT_KEY }}|g" ./.github/workflows/overall_code_analysis_decoration.md
          sed -i "s|{{SONAR_PROJECT_BADGE_TOKEN}}|${{ env.SONAR_PROJECT_BADGE_TOKEN }}|g" ./.github/workflows/overall_code_analysis_decoration.md

          if echo "$status" | grep -q '"status":"ERROR"'; then
            echo "Quality Gate status on overall code: Failed!"
            QGstatus=$(cat ./.github/workflows/overall_code_analysis_decoration.md)
          elif echo "$status" | grep -q '"status":"WARN"'; then
            echo "Quality Gate status on overall code: Warnings!"
            QGstatus=$(echo "Quality Gate status on overall code: Warning!")
          elif echo "$status" | grep -q '"status":"OK"'; then
            echo "Quality Gate status on overall code: Passed!"
            QGstatus=$(cat ./.github/workflows/overall_code_analysis_decoration.md)
          else
            echo "Unknown Quality Gate status on overall code"
            QGstatus=$(echo "Unknown Quality Gate status on overall code")
          fi
          echo "QGSTATUS=$QGstatus" >> $GITHUB_ENV

      - name: Create comment with validation result
        id: create_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const timestamp = new Date().getTime();
            const output = `${{ steps.QG_check.outputs.QGSTATUS }} \n PR Number: ${{ github.event.pull_request.number }} \n Branch Name: ${{ github.head_ref }} \n Please refer below link for Sonar analysis report on overall code: ${{ env.SONAR_HOST_URL }}/dashboard?branch=${{ github.head_ref }}&id=${{ env.SONAR_PROJECT_KEY }}`;
            const commentBody = output + "\n\n<!-- Comment Identifier: " + timestamp + " -->";

            const existingComment = context.payload.pull_request.body.match(/<!-- Comment Identifier: \d+ -->/g);
            const filteredBody = existingComment ? context.payload.pull_request.body.replace(existingComment[0], "") : context.payload.pull_request.body;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: filteredBody + "\n\n" + commentBody
            }).then(response => {
              const commentId = response.data.id;
              core.setOutput('comment_id', commentId);
            });
